In [1]:
import numpy as np
import time 
import math
import sys

In [52]:
#implementation of insertion sort algorithm
def insertion_sort(unsorted_is):
    for j in range(1, unsorted_is.shape[0]):
        key = unsorted_is[j]
        i = j-1
        while i>-1 and unsorted_is[i]>=key:
            unsorted_is[i+1] = unsorted_is[i]
            i-=1
            
        unsorted_is[i+1] = key
    
    return unsorted_is

In [53]:
##test for insertion sort algorithm implementation
array_size = 5
array_end = 10
array_start = 1
ins_sort = np.random.randint(array_start, high= array_end, size= array_size)#np.array([1,4,5,2,9,3])
print (ins_sort)

start_time = time.time()
ins_sort = insertion_sort(ins_sort)
end_time = time.time()
ins_sort_run_time = end_time - start_time

print (ins_sort)
print ("sorted in %s seconds" %(ins_sort_run_time))

[6 1 1 9 8]
[1 1 6 8 9]
sorted in 0.00015163421630859375 seconds


In [75]:
#implementation of selection sort algorithm
def selection_sort(unsorted_ss):
    for i in range(unsorted_ss.shape[0] - 1):
        lowindex = i #unsorted_ss_min = unsorted_ss[i]
        for j in reversed(range(i + 1, unsorted_ss.shape[0])):
            if unsorted_ss[j]<unsorted_ss[lowindex]:
                lowindex=j #unsorted_ss[i] = unsorted_ss[j]
                #unsorted_ss[j] = unsorted_ss_min
        unsorted_ss[i], unsorted_ss[lowindex] = unsorted_ss[lowindex], unsorted_ss[i]
    
        
    return unsorted_ss

In [78]:
##test for selection sort algorithm implementation
array_size = 5
array_end = 10
array_start = 1
sel_sort = np.random.randint(array_start, high= array_end, size= array_size)#np.array([1,4,5,2,9,3])
print (sel_sort)

start_time = time.time()
sel_sort = selection_sort(sel_sort)
end_time = time.time()
sel_sort_run_time = end_time - start_time

print (sel_sort)
print ("sorted in %s seconds" %(sel_sort_run_time))

[9 9 6 9 5]
[5 6 9 9 9]
sorted in 5.8650970458984375e-05 seconds


In [150]:
###implementation of merge sort algorithm

#definition of merge function
def merge(left_sub_array, right_sub_array):
    merged_array = np.zeros(left_sub_array.shape[0] + right_sub_array.shape[0])
    
    left_index = 0
    right_index = 0
    
    for i in range(merged_array.shape[0]):
        if left_sub_array[left_index] <= right_sub_array[right_index] :
            merged_array[i] = left_sub_array[left_index]
            if not (left_index + 1) >= left_sub_array.shape[0]:
                left_index +=1
            else:
                left_sub_array[left_index] = sys.maxsize #sys.maxsize used as ininfity integer number
        else :
            merged_array[i] = right_sub_array[right_index]
            if not (right_index + 1) >= right_sub_array.shape[0]:
                right_index +=1
            else:
                right_sub_array[right_index] = sys.maxsize
            
    #merged_array = np.concatenate((left_sub_array, right_sub_array), axis=0)
    #left_index = 0
    #right_index = left_sub_array.shape[0]
    
    #for i in range(merged_array.shape[0]):
    #    if merged_array[left_index] <= merged_array[right_index] :
    #        merged_array[left_index], merged_array[right_index] = merged_array[right_index], merged_array[left_index]
    #        left_index +=1
    #    else :
    #        merged_array[right_index], merged_array[left_index] = merged_array[left_index], merged_array[right_index]
    #        if not (right_index + 1) >= merged_array.shape[0]:
    #            right_index +=1
            
    
    return merged_array

#definition of merge_sort function
def merge_sort(unsorted_ms):
    if unsorted_ms.shape[0] == 1 :
        return unsorted_ms
    else :
        L_sub_array, R_sub_array = np.array_split(ary=unsorted_ms, indices_or_sections=2)
        
        L_sub_array = merge_sort(L_sub_array)
        R_sub_array = merge_sort(R_sub_array)
        
        return merge(L_sub_array, R_sub_array)

In [154]:
##test for merge sort algorithm implementation
array_size = 8
array_end = 10
array_start = 1
mer_sort = np.random.randint(array_start, high= array_end, size= array_size)#np.array([1,4,5,2,9,3])
print (mer_sort)

start_time = time.time()
mer_sort = merge_sort(mer_sort)
end_time = time.time()
mer_sort_run_time = end_time - start_time

print (mer_sort)
print ("sorted in %s seconds" %(mer_sort_run_time))

[3 5 5 9 1 9 4 3]
[ 1.  3.  3.  4.  5.  5.  9.  9.]
sorted in 0.00024271011352539062 seconds


In [21]:
### implementation of quick sort algorithm

#definition of artition function
def partition (unpartitioned):
    unpartitioned_size = unpartitioned.shape[0]
    
    pivot = unpartitioned[unpartitioned_size - 1]
    min_index = -1
    
    for i in range(unpartitioned_size-1):
        if unpartitioned[i] <= pivot :
            min_index += 1
            unpartitioned[min_index], unpartitioned[i] = unpartitioned[i], unpartitioned[min_index]
            
    unpartitioned[min_index + 1], unpartitioned[unpartitioned_size - 1] = unpartitioned[unpartitioned_size - 1], unpartitioned[min_index + 1]
    
    return min_index + 1 , unpartitioned

def quick_sort(unsorted_qs):
    if unsorted_qs.shape[0] <= 1 :
        return unsorted_qs
    else:
        partition_index, unsorted_qs = partition(unsorted_qs)
        left_qs = unsorted_qs[:partition_index]
        pivot_qs = np.array((1,))
        pivot_qs[0] = unsorted_qs[partition_index]
        right_qs = unsorted_qs[partition_index + 1 :]
        
        left_qs = quick_sort(left_qs)
        right_qs = quick_sort(right_qs)
        
        return np.concatenate((left_qs, pivot_qs, right_qs))
        

In [23]:
##test for quick sort algorithm implementation
array_size = 8
array_end = 10
array_start = 1
qs_sort = np.random.randint(array_start, high= array_end, size= array_size)#np.array([1,4,5,2,9,3])
print (qs_sort)

start_time = time.time()
qs_sort = quick_sort(qs_sort)
end_time = time.time()
qs_sort_run_time = end_time - start_time

print (qs_sort)
print ("sorted in %s seconds" %(qs_sort_run_time))

[9 3 4 7 4 5 5 6]
[3 4 4 5 5 6 7 9]
sorted in 0.0001437664031982422 seconds


In [18]:
a = np.array([1,2,3])
b = np.zeros(3)
d = np.array((1,))
d[0] = a[0]
c = np.concatenate((a,b,d), axis=0)
a.shape
for j in range(len(a)):
    print (a[j])

print (a)
a.shape[0]
l, r=np.array_split(ary=a,indices_or_sections=2)
print(l.shape, r.shape, d.shape)
c

1
2
3
[1 2 3]
(2,) (1,) (1,)


array([ 1.,  2.,  3.,  0.,  0.,  0.,  1.])

In [14]:
np.array?

In [11]:
a = np.random.randint(1,10,3)
if a.shape[0] == 2 :
    print("hi")
else :
    print(a)

a[:2], a[1:]



[9 2 3]


(array([9, 2]), array([2, 3]))

In [1]:
r =int (1)
if not (r + 1) >= 3:
    r +=1
    
print (r)

r

2


NameError: name 'Decimal' is not defined