In [17]:
import numpy as np
import time 

In [52]:
#implementation of insertion sort algorithm
def insertion_sort(unsorted_is):
    for j in range(1, unsorted_is.shape[0]):
        key = unsorted_is[j]
        i = j-1
        while i>-1 and unsorted_is[i]>=key:
            unsorted_is[i+1] = unsorted_is[i]
            i-=1
            
        unsorted_is[i+1] = key
    
    return unsorted_is

In [53]:
##test for insertion sort algorithm implementation
array_size = 5
array_end = 10
array_start = 1
ins_sort = np.random.randint(array_start, high= array_end, size= array_size)#np.array([1,4,5,2,9,3])
print (ins_sort)

start_time = time.time()
ins_sort = insertion_sort(ins_sort)
end_time = time.time()
ins_sort_run_time = end_time - start_time

print (ins_sort)
print ("sorted in %s seconds" %(ins_sort_run_time))

[6 1 1 9 8]
[1 1 6 8 9]
sorted in 0.00015163421630859375 seconds


In [75]:
#implementation of selection sort algorithm
def selection_sort(unsorted_ss):
    for i in range(unsorted_ss.shape[0] - 1):
        lowindex = i #unsorted_ss_min = unsorted_ss[i]
        for j in reversed(range(i + 1, unsorted_ss.shape[0])):
            if unsorted_ss[j]<unsorted_ss[lowindex]:
                lowindex=j #unsorted_ss[i] = unsorted_ss[j]
                #unsorted_ss[j] = unsorted_ss_min
        unsorted_ss[i], unsorted_ss[lowindex] = unsorted_ss[lowindex], unsorted_ss[i]
    
        
    return unsorted_ss

In [78]:
##test for selection sort algorithm implementation
array_size = 5
array_end = 10
array_start = 1
sel_sort = np.random.randint(array_start, high= array_end, size= array_size)#np.array([1,4,5,2,9,3])
print (sel_sort)

start_time = time.time()
sel_sort = selection_sort(sel_sort)
end_time = time.time()
sel_sort_run_time = end_time - start_time

print (sel_sort)
print ("sorted in %s seconds" %(sel_sort_run_time))

[9 9 6 9 5]
[5 6 9 9 9]
sorted in 5.8650970458984375e-05 seconds


In [79]:
np.split?

In [84]:
a = np.array([1,2,3])
a[0]
a.shape
for j in range(len(a)):
    print (a[j])

print (a)
a.shape[0]
l, r=np.array_split(ary=a,indices_or_sections=2)
print(l.shape, r.shape)

1
2
3
[1 2 3]
(2,) (1,)
