## Syntax checking codes

In [3]:
import numpy as np
import csv


In [20]:
print(a)
print(np.transpose(a))
print(a)

[[ 1  2  3  4]
 [20  7  5  8]
 [ 0  2  4  9]]
[[ 1 20  0]
 [ 2  7  2]
 [ 3  5  4]
 [ 4  8  9]]
[[ 1  2  3  4]
 [20  7  5  8]
 [ 0  2  4  9]]


In [ ]:
# Python program for implementation of Quicksort 

# This function is same in both iterative and recursive 
def partition(arr,l,h): 
	i = ( l - 1 ) 
	x = arr[h] 

	for j in range(l , h): 
		if arr[j] <= x: 

			# increment index of smaller element 
			i = i+1
			arr[i],arr[j] = arr[j],arr[i] 

	arr[i+1],arr[h] = arr[h],arr[i+1] 
	return (i+1) 

# Function to do Quick sort 
# arr[] --> Array to be sorted, 
# l --> Starting index, 
# h --> Ending index 
def quickSortIterative(arr,l,h): 

	# Create an auxiliary stack 
	size = h - l + 1
	stack = [0] * (size) 

	# initialize top of stack 
	top = -1

	# push initial values of l and h to stack 
	top = top + 1
	stack[top] = l #stack[0]
	top = top + 1
	stack[top] = h #stack[1]

	# Keep popping from stack while is not empty 
	while top >= 0: 

		# Pop h and l 
		h = stack[top] 
		top = top - 1
		l = stack[top] 
		top = top - 1

		# Set pivot element at its correct position in 
		# sorted array 
		p = partition( arr, l, h ) 

		# If there are elements on left side of pivot, 
		# then push left side to stack 
		if p-1 > l: 
			top = top + 1
			stack[top] = l 
			top = top + 1
			stack[top] = p - 1

		# If there are elements on right side of pivot, 
		# then push right side to stack 
		if p+1 < h: 
			top = top + 1
			stack[top] = p + 1
			top = top + 1
			stack[top] = h 

# Driver code to test above 
arr = [4, 3, 5, 2, 1, 3, 2, 3] 
n = len(arr) 
quickSortIterative(arr, 0, n-1) 
print ("Sorted array is:") 
for i in range(n): 
	print ("%d" %arr[i]), 

# This code is contributed by Mohit Kumra 


In [27]:
a = np.array([1,2,3,4])
#np.savetxt("mycsv.csv", a, delimiter=",")
#np.reshape(a, (4,3))
a.shape[0]

4

In [ ]:
a = [1,2,3]
for i in a[1:]:
    print(i)

for i in range(len(dict0)):
    #print (i)

dict0 = {0:np.array([1])}
j = 1
for i in interval_array[1:]:
    dict0[j] = np.flip(np.sort(np.random.randint(0, high=i, size=i)), axis=0)
    j += 1
print(dict0)
print(len(dict0))

dict0_sorted={}
rt0 = np.zeros((5,21))
#for sorter in sorter_alg:
for intervals in range(len(dict0)):
    #if sorter=="insertion_sort":
    start_time = time.time()
    dict0_sorted[intervals] = insertion_sort(dict0[intervals])
    end_time = time.time()
    rt0[0][intervals] = end_time - start_time
    
print(dict0)
print(dict0_sorted)
print(rt0[0][:])
print(len(rt0[0][:]))

In [ ]:
dictionery = {0:np.array([1,2,3]), '1':'ethiopian'}
for i in dictionery:
    print (dictionery[i])
    if i == 0:
        print(dictionery[i].shape)
    

a0_5 = timeit.timeit(heap_sort(np.array([6 ,1 ,7])))
a0_5

A = np.arange(100,-2,-2)
B = np.random.randint(0,20000000,100000)
A.size
B.size

a = np.array([1,2,3])
b = np.zeros(3)
d = np.array((1,))
d[0] = a[0]
e = np.array([a[0]])
c = np.concatenate((a,b,d, e), axis=0)
a.shape
for j in range(len(a)):
    print (a[j])

print (a)
a.shape[0]
l, r=np.array_split(ary=a,indices_or_sections=2)
print(l.shape, r.shape, d.shape)
c

np.array?

a = np.random.randint(1,10,3)
if a.shape[0] == 2 :
    print("hi")
else :
    print(a)

a[2:]



r =int (1)
if not (r + 1) >= 3:
    r +=1
    
print (r)

r

a = np.array([1])
a.shape
b = np.random.randn(3,2)
print(b)
b = np.ceil(b)
print(b)
a.shape
a

np.random.randint?

np.sort?

start = 0
stop = 200
step = 20
range_step = int(stop/step)

interval_array = np.empty((0,1), dtype=int)
for i in range(start, stop+1, range_step):
    interval_array = np.append(interval_array, int(i))
    
interval_array #each value in this array is the stop value for generating random numbers in the range 0 - some_num
    
##############################################
trial_test_array = np.random.randint(0, high=20, size=10) #initialize test array with presotedness = 0.5
#np.random.shuffle(trial_test_array) #presotedness = 0.5
print(trial_test_array)

trial_test_array = np.sort(trial_test_array) #presortedness = 1
print(trial_test_array)

trial_test_array = np.flip(trial_test_array, axis=0) #presortedness = 0 run it right after presortedness is 1
print(trial_test_array)
####################################################

#runtime for presortedness of 0
presortedness = [0, 0.5, 1]
rep = 5
sorter_alg = ["insertion_sort", "selection_sort", "merge_sort", "quick_sort", "heap_sort"]
sorter_alg_run_time = np.zeros((5,21)) #number of algorithms by number of intervals
#for sorter in sorter_alg:
#    for i in interval_array: #for each interval
#        for j in presortedness: #for each degree of sortedness
            
            
######################

## Tests on algorithm 

In [ ]:
##test for insertion sort algorithm implementation
array_size = 5
array_end = 10
array_start = 1
ins_sort = np.random.randint(array_start, high= array_end, size= array_size)
print (ins_sort)

start_time = time.time()
ins_sort = insertion_sort(ins_sort)
end_time = time.time()
ins_sort_run_time = end_time - start_time

print (ins_sort)
print ("sorted in %s seconds" %(ins_sort_run_time))

In [ ]:
##test for selection sort algorithm implementation
array_size = 10000
array_end = 1000000
array_start = 1
sel_sort = np.random.randint(array_start, high= array_end, size= array_size)#np.array([1,4,5,2,9,3])
print (sel_sort)

start_time = time.time()
sel_sort = selection_sort(sel_sort)
end_time = time.time()
sel_sort_run_time = end_time - start_time

print (sel_sort)
print ("sorted in %s seconds" %(sel_sort_run_time))

In [ ]:
##test for merge sort algorithm implementation
array_size = 8
array_end = 10
array_start = 1
mer_sort = np.random.randint(array_start, high= array_end, size= array_size)#np.array([1,4,5,2,9,3])
print (mer_sort)

start_time = time.time()
mer_sort = merge_sort(mer_sort)
end_time = time.time()
mer_sort_run_time = end_time - start_time

print (mer_sort)
print ("sorted in %s seconds" %(mer_sort_run_time))

In [ ]:
##test for quick sort algorithm implementation
array_size = 8
array_end = 10
array_start = 1
qs_sort = np.random.randint(array_start, high= array_end, size= array_size)#np.array([1,4,5,2,9,3])
print (qs_sort)

start_time = time.time()
qs_sort = quick_sort(qs_sort)
end_time = time.time()
qs_sort_run_time = end_time - start_time

print (qs_sort)
print ("sorted in %s seconds" %(qs_sort_run_time))

In [ ]:
##test for heap sort algorithm implementation
array_size = 8
array_end = 10
array_start = 1
hs_sort = np.random.randint(array_start, high= array_end, size= array_size)#np.array([1,4,5,2,9,3])
print (hs_sort)

start_time = time.time()
hs_sort = heap_sort(hs_sort)
end_time = time.time()
hs_sort_run_time = end_time - start_time

print (hs_sort)
print ("sorted in %s seconds" %(hs_sort_run_time))